include:
  - postgres-compose.yml
  - docker-compose.yml
services:
  app:
    build:
      context: ../
      dockerfile: ./docker-elk-main/project.Dockerfile
    container_name: translation_app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_CONTAINER_NAME: $POSTGRES_CONTAINER_NAME
      YANDEX_KEY: $YANDEX_KEY
    depends_on:
      liquibase-migrations:
        condition: service_completed_successfully
      postgresql:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - app
          - logstash